### ISSUE TITLE
Tutorial Page

### ISSUE THREAD

**Issue by jlcasasg** [IBIS-DEVS/ibis-te-escucha#2]
This page will contain slides that will show the functionalities of the application.

**Comment by JuanSeBestia** [comment]
Slide:1 Logo + Slogan

**Comment by jlcasasg** [comment]
Ejemplo de quienes somos:
Somos un grupo de ayuda encargado de orientar y escuchar las dificultades e inconvenientes sobre violencia sexual en el transporte público con el cual brindamos un espacio de acompañamiento dónde no te sentirás juzgad@, discrimanad@, si no simplemente escuchad@ y orientad@

**Comment by jlcasasg** [comment]
Slide 2: Información sobre anonimato
Slide 3: Texto sobre testimonios
Slide 4: Texto sobre chat de expertos
Slide 5: texto sobre canales de ayuda

**Comment by JuanSeBestia** [comment]
La primerá imagen no me gustó tanto :/

**Comment by JuanSeBestia** [comment]
Quizás el botón del final puede decir Go, Ir, Vamos, Empezar

Y quizas muuuucho más grande!
